In [1]:
import pandas as pd
import os as csv

In [2]:
# Path to February data
path1 = "JC-202002-citibike-tripdata.csv/JC-202002-citibike-tripdata.csv"
# Read csv file
csv_file1 = pd.read_csv(path1)
# Turn csv file to dataframe
February = pd.DataFrame(csv_file1)
February

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22957,262,2020-02-29 23:40:53.1620,2020-02-29 23:45:15.3180,3639,Harborside,40.719252,-74.034234,3214,Essex Light Rail,40.712774,-74.036486,42467,Subscriber,1967,1
22958,216,2020-02-29 23:41:01.3350,2020-02-29 23:44:38.0350,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42377,Subscriber,1958,1
22959,101,2020-02-29 23:45:22.1700,2020-02-29 23:47:03.2970,3214,Essex Light Rail,40.712774,-74.036486,3681,Grand St,40.715178,-74.037683,42485,Subscriber,1967,1
22960,279,2020-02-29 23:47:56.8380,2020-02-29 23:52:36.6400,3186,Grove St PATH,40.719586,-74.043117,3483,Montgomery St,40.719420,-74.050990,42531,Subscriber,1988,1
22961,212,2020-02-29 23:49:18.4510,2020-02-29 23:52:50.7490,3184,Paulus Hook,40.714145,-74.033552,3276,Marin Light Rail,40.714584,-74.042817,42385,Subscriber,1967,1

In [3]:
# Path to March data
path2 = "JC-202003-citibike-tripdata.csv/JC-202003-citibike-tripdata.csv"
# Read csv file
csv_file2 = pd.read_csv(path2)
# Turn csv file to dataframe
March = pd.DataFrame(csv_file2)
March

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01 00:14:07.0000,2020-03-01 00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01 00:48:06.4390,2020-03-01 00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01 01:08:46.4880,2020-03-01 01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01 01:22:35.4790,2020-03-01 01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01 01:39:20.2680,2020-03-01 01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17714,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1
17715,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1
17716,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1
17717,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1
17718,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1

In [4]:
# Path to April data
path3 = "JC-202004-citibike-tripdata.csv/JC-202004-citibike-tripdata.csv"
# Read csv file
csv_file3 = pd.read_csv(path3)
# Turn csv file to dataframe
April = pd.DataFrame(csv_file3)
April

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01 01:06:20.6300,2020-04-01 01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01 05:02:42.0570,2020-04-01 05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01 06:20:28.1190,2020-04-01 06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01 06:33:30.5170,2020-04-01 06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01 06:38:32.9220,2020-04-01 06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9263,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0
9264,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1
9265,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1
9266,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1
9267,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1

In [5]:
# Append March dataframe to February dataframe
February_March = February.append(March, ignore_index=True)
February_March

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40676,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1
40677,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1
40678,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1
40679,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1
40680,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1

In [6]:
# Append April dataframe to February_March dataframe
February_April = February_March.append(April, ignore_index=True)
February_April

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49944,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0
49945,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1
49946,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1
49947,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1
49948,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1

In [7]:
# Create new column with date by splitting startime column and using first string
February_April["Date"] = February_April["starttime"].str.split(' ', 1, expand=True)[0]
February_April

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Date
0,841,2020-02-01 00:02:13.7650,2020-02-01 00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1,2020-02-01
1,206,2020-02-01 00:16:11.3850,2020-02-01 00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1,2020-02-01
2,859,2020-02-01 00:23:22.1090,2020-02-01 00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1,2020-02-01
3,693,2020-02-01 00:25:14.5170,2020-02-01 00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1,2020-02-01
4,1473,2020-02-01 00:32:30.5050,2020-02-01 00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0,2020-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49944,597,2020-04-30 22:18:40.4140,2020-04-30 22:28:38.1280,3678,Fairmount Ave,40.725726,-74.071959,3279,Dixon Mills,40.721630,-74.049968,42240,Customer,1969,0,2020-04-30
49945,311,2020-04-30 22:23:18.7780,2020-04-30 22:28:30.2980,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42535,Subscriber,1986,1,2020-04-30
49946,167,2020-04-30 22:34:51.8480,2020-04-30 22:37:39.6690,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42615,Subscriber,1991,1,2020-04-30
49947,520,2020-04-30 22:50:52.2380,2020-04-30 22:59:33.1620,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42403,Subscriber,1976,1,2020-04-30
49948,1043,2020-04-30 22:54:39.0840,2020-04-30 23:12:02.1790,3191,Union St,40.718211,-74.083639,3275,Columbus Drive,40.718355,-74.038914,42255,Customer,1999,1,2020-04-30

In [9]:
# Save dataframe as csv file without index
February_April.to_csv("Feb_Apr1.csv", index=False)